services:
  postgres:
    image: postgres:16-alpine
    container_name: product-manager-postgres
    environment:
      POSTGRES_DB: product-manager
      POSTGRES_USER: product-manager
      POSTGRES_PASSWORD: product-manager
    ports:
      - "5432:5432"
    volumes:
      - product-manager_pgdata:/var/lib/postgresql/data

volumes:
  product-manager_pgdata:
